module.exports = {
  fieldgoal: {
    eliteClassification: 0.075,
    greatClassification: 0.03,
    goodClassification: 0,
    badClassification: -0.02,
    horribleClassification: -0.05,
  },
  freethrow: {
    eliteClassification: 0.15,
    greatClassification: 0.08,
    goodClassification: 0.03,
    badClassification: -0.00875,
    horribleClassification: -0.0425,
  },
  threePoint: {
    eliteClassification: 4,
    greatClassification: 3,
    goodClassification: 2,
    badClassification: 1.5,
    horribleClassification: 1,
  },
  point: {
    eliteClassification: 30,
    greatClassification: 25,
    goodClassification: 20,
    badClassification: 15,
    horribleClassification: 10,
  },
  rebound: {
    eliteClassification: 10,
    greatClassification: 9,
    goodClassification: 7,
    badClassification: 5,
    horribleClassification: 3,
  },
  assist: {
    eliteClassification: 8,
    greatClassification: 6,
    goodClassification: 4,
    badClassification: 2,
    horribleClassification: 1,
  },
  steal: {
    eliteClassification: 2,
    greatClassification: 1.5,
    goodClassification: 1,
    badClassification: 0.7,
    horribleClassification: 0.5,
  },
  block: {
    eliteClassification: 1.5,
    greatClassification: 1.2,
    goodClassification: 0.8,
    badClassification: 0.5,
    horribleClassification: 0.3,
  },
  turnover: {
    eliteClassification: 0.7,
    greatClassification: 1,
    goodClassification: 1.5,
    badClassification: 2,
    horribleClassification: 3,
  }
};
